# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1052, 782)
        Form.setStyleSheet("background-color: rgb(10, 92, 143)")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 380, 221, 51))
        self.label_3.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.comboBox1 = QtWidgets.QComboBox(Form)
        self.comboBox1.setGeometry(QtCore.QRect(340, 400, 521, 31))
        self.comboBox1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox1.setObjectName("comboBox")
        self.nocard = QtWidgets.QPushButton(Form)
        self.nocard.setGeometry(QtCore.QRect(60, 490, 291, 91))
        self.nocard.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Times New Roman\";")
        self.nocard.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 620, 291, 91))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 650, 251, 51))
        self.label_4.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(320, 50, 541, 31))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 40, 221, 51))
        self.label_5.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 100, 341, 111))
        self.label_6.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.time = QtWidgets.QTextEdit(Form)
        self.time.setGeometry(QtCore.QRect(430, 150, 421, 51))
        self.time.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.time.setObjectName("time")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(430, 220, 541, 91))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(330, 220, 91, 51))
        self.label_7.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Выбирите карту:"))
