# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1048, 795)
        Form.setStyleSheet("background-color: rgb(10, 92, 143);")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 140, 425, 355))
        self.tableWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.buyp = QtWidgets.QPushButton(Form)
        self.buyp.setGeometry(QtCore.QRect(730, 670, 291, 91))
        self.buyp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Times New Roman\";")
        self.buyp.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 650, 91, 51))
        self.label.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 710, 251, 51))
        self.label_2.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(320, 650, 111, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(320, 700, 111, 41))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(280, 60, 421, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 241, 51))
        self.label_3.setStyleSheet("font: 75 italic 20pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.save=QtWidgets.QPushButton(Form)
        self.save.setGeometry(QtCore.QRect(740,40,291,91))
        self.save.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "font: 75 20pt \"Times New Roman\";")
        self.save.setObjectName("pushButton_2")
        self.save.setText('Сохранить')


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.buyp.setText(_translate("Form", "Оплатить"))
        self.label.setText(_translate("Form", "Сумма:"))
        self.label_2.setText(_translate("Form", "Количество позиций:"))
        self.label_3.setText(_translate("Form", "Выбирите позицию:"))
